# epsilon-runtime

Eclipse Epsilon Runtime for Maven and OSGi. There are builders and helper classes, 
URI handlers that can help the usage of Epsilon out of Eclipse ecosystem. 

## What is Epsilon?

From: https://www.eclipse.org/epsilon/

Epsilon is a family of languages and tools for code generation, model-to-model transformation, 
model validation, comparison, migration and refactoring that work out of the box with EMF, 
UML, Simulink, XML and other types of models.

## Example

1. Define a meta-model. The meta-model contains the definition of our structure:

:testmodels: epsilon-runtime/epsilon-runtime-test-model/model

[source, xml]
----
include::{testmodels}/epsilon-runtime-test.ecore[]
----

[NOTE]
====
In EMF (Emfatic fomat) - You can convert between .ecore and .emf within eclipse. 
The epsilon-runtime will support emfatic format directly soon.
====

----
@namespace(uri="http://www.blackbelt.hu/epsilon-runtime/test", prefix="data")
package data;

class DataModel {
  attr String name;
  val Entity[*] entity;
}

class Entity { <1>
  attr String name;
  val Attribute[+] attribute;
  val EntityReference[*] reference;
}

class Attribute { <2>
  attr String name;
  attr String type;
}

class EntityReference { <3>
  attr String name;
  attr boolean toMany;
  ref Entity[1] target;
}
----
<1> Entity - Represents a class 
<2> Attribute - Represents an attribute of class
<3> Reference - Represents a reference to a class


