# epsilon-runtime

Eclipse Epsilon Runtime for Maven and OSGi. There are builders and helper classes, 
URI handlers that can help the usage of Epsilon out of Eclipse ecosystem. 

## What is Epsilon?

From: https://www.eclipse.org/epsilon/

Epsilon is a family of languages and tools for code generation, model-to-model transformation, 
model validation, comparison, migration and refactoring that work out of the box with EMF, 
UML, Simulink, XML and other types of models.

## Example

1. Define a meta-model. The meta-model contains the definition of our structure:

[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="data" nsURI="http://www.blackbelt.hu/epsilon-runtime/test" nsPrefix="data">
  <eClassifiers xsi:type="ecore:EClass" name="DataModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" upperBound="-1"
        eType="#//Entity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1"
        upperBound="-1" eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" upperBound="-1"
        eType="#//EntityReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityReference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toMany" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Entity"/>
  </eClassifiers>
</ecore:EPackage>
----

[NOTE]
====
In EMF (Emfatic fomat) - You can convert between .ecore and .emf within eclipse. 
The epsilon-runtime will support emfatic format directly soon.
====

----
@namespace(uri="http://www.blackbelt.hu/epsilon-runtime/test", prefix="data")
package data;

class DataModel {
  attr String name;
  val Entity[*] entity;
}

class Entity { // <1>
  attr String name;
  val Attribute[+] attribute;
  val EntityReference[*] reference;
}

class Attribute { // <2>
  attr String name;
  attr String type;
}

class EntityReference { // <3>
  attr String name;
  attr boolean toMany;
  ref Entity[1] target;
}
----
<1> Entity - Represents a class 
<2> Attribute - Represents an attribute of class
<3> Reference - Represents a reference to a class


